name: Generate Repository Cards

# Dogfooding
# uses its own action as usage example

on:
  workflow_dispatch:  # Allow manual triggers
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Mondays

permissions:
  contents: write  # Needed for pushing changes

jobs:
  generate-cards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Generate repository cards
        uses: metaory/github-repo-cards@v1
        with:
          repositories: |
            repo-cards
            dotfiles
          theme: default   # Pick a theme SVG (default: default)
          output: cards       # Output directory (default: cards)
          format: svg    # svg (default, text as paths) or png
          # accent: '#FF88EE' # Optional accent color
          avatar: |
            style=glass
            radius=28
            backgroundType=gradientLinear
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
